version: '3.3'

services:
  api:
    build:
      context: ../api
      dockerfile: ./api.dev.Dockerfile
    container_name: Hawk-api
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 4000
    ports:
      - 4000:4000
    # env_file: ../.env
    environment:
      WAIT_HOSTS: db:27018,redis:6379
      WAIT_HOSTS_TIMEOUT: 120
      # mongo and redis hoste env variables
      MONGO_URI: mongodb://db:27017/hawk
      REDIS_HOST: redis
      PORT: 4000
      MAX_LEVEL: 5
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    container_name: Hawk-db
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
    networks:
      - network
    logging:
      driver: none

  redis:
    image: redis:alpine
    container_name: Hawk-redis
    restart: unless-stopped
    networks:
      - network

  client:
    stdin_open: true
    build:
      context: ../client
      dockerfile: ./client.prod.Dockerfile
    container_name: Hawk-client
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../client:/usr/src/client
    ports:
      - 3005:3000
    environment:
      REACT_APP_LEVEL_COUNT: 5
    # CLIENT WONT START UP TILL API HAS STARTED (uncomment for this)
    # depends_on:
    #   - api

networks:
  network:
    driver: bridge
